### ISSUE TITLE
New Check Request

### ISSUE THREAD

**Issue by pvienhage** [rahul-kothari/hack-money-ape#29]
https://github.com/rahul-kothari/hack-money-ape/blob/081a9cc1b63d26c0c3afc1313419f3dd6b321da4/contracts/YieldTokenCompounding.sol#L52

I think it would be more secure to have a check here which either checks that (1) the user has more than some user supplied balance of underlying or (2) that there's more than some user supplied PT value

**Comment by mattiaslightstone** [comment]
Just confirming that this is to prevent the following:

Lets say we have a transaction that we simulate.
100 USDC -> 90 USDC + 400 YTs.

Here 400YTs cost 10USDC. We verify that we receive lets say 396YTs (1% slippage), but we don't check how much it cost.

Thus a valid transaction could be
100 USDC -> 10 USDC + 400 YTs. Which would be a huge loss.

**Comment by mattiaslightstone** [comment]
I'm implementing this as such:

Slippage tolerance will refer to the the movement of both the Yield Tokens Received and the Base Tokens Spent.

This means that 1% slippage will allow up to a 0.5% decrease in the number of YTs received, and 0.5% increase in the number of BTs spent.

This seems inelegant, but I'm not sure of the better way to do it.

**Comment by pvienhage** [comment]
Generally it's inelegant and inefficient to try to use percent slippage on chain, my suggesstion instead would be to take 'endBalanceUnderlying' and 'endBalancePT' as arguments and then check that the user has greater or equal to those values of the respective token after the call. The front end then can do calculations to ensure safe numbers are used.

**Comment by mattiaslightstone** [comment]
Sorry I've mixed two ideas together here.

1. In the contracts i've added an additional check for the difference in starting balance and ending balance of underlying tokens.

2. In the frontend the values are being calculated based off of the user's selection of slippage tolerance, split 50/50 between YTs received and BTs spent.

I have a concern with using endBalanceUnderlying or endBalancePT. It does not take into account that balance can change between a transaction being signed and being executed.

1. You send a transaction where you have 100 underlying tokens, that expects your endBalanceUnderlying to be 80.
2. Before your transaction is confirmed, you receive 100 underlying tokens in payment for some other activity (balance 200).
3. The transaction would now be valid even with extreme slippage (120 underlying tokens, rather than 20).

**Comment by pvienhage** [comment]
Yeah fair enough, it's good this way 👍
